export { default as Blog } from './blog/Blog';
export { default as Features } from './features/Features';
export { default as Footer } from './footer/Footer';
export { default as Header } from './header/Header';
export { default as Mission } from './mission/Mission';
export { default as Discord } from './discord/Discord';
export { default as Contact } from './contact/Contact';
export { default as Aboutpage } from './aboutpage/Aboutpage';
export { default as Partnership } from './partnership/Partnership';